server:
  port: 8080

spring:
  application:
    name: seckill-gateway
  config:
    import: optional:nacos:${spring.cloud.nacos.config.server-addr:127.0.0.1:8848}

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: seckill-seller
          uri: lb://seckill-user
          predicates:
            - Path=/api/seller/**
          filters:
            - StripPrefix=1
        - id: seckill-user
          uri: lb://seckill-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: seckill-goods
          uri: lb://seckill-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=1
        - id: seckill-order
          uri: lb://seckill-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers:
              - Authorization
              - X-User-Id

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.seckill.gateway: debug
    org.springframework.cloud.gateway: debug
